Name = program_01

CXX = c++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

CPPFILES = Fixed.cpp main.cpp

all:
	$(CXX) $(CPPFLAGS) $(CPPFILES) -o $(Name)

clear:
	rm -rf $(Name)

fclean:
	rm -rf $(Name)
