Name = robot

CXX = c++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

CPPFILS = main.cpp ClapTrap.cpp


all:
	$(CXX) $(CPPFLAGS) $(CPPFILS) -o $(Name)

clean:
	rm -rf $(Name)

fclean:
	rm -rf $(Name)

re : fclean all