Name = convert

CPPFILS = main.cpp ScalarConverter.cpp

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

all:
	c++ $(CPPFLAGS) $(CPPFILS) -o $(Name)

clean:
	rm -rf $(Name)

fclean:
	rm -rf $(Name)

re: fclean all