Name = Form_process

CPPFILS = AForm.cpp PresidentialPardonForm.cpp ShrubberyCreationForm.cpp\
		Bureaucrat.cpp RobotomyRequestForm.cpp  main.cpp

all:
	c++ -Wall -Wextra -Werror -std=c++98 $(CPPFILS) -o $(Name)

clean:
	rm -rf $(Name)

fclean:
	rm -rf $(Name)

re : fclean all
