Name = Span_l_s

CPPFILS = main.cpp Span.cpp

CPPFLAGS = -Wall -Wextra -Werror -std=c++98 #-fsanitize=address

all:
	c++ $(CPPFLAGS) $(CPPFILS) -o $(Name)

clean:
	rm -rf $(Name)

fclean:
	rm -rf $(Name)

re: fclean all