Name = program 

CXX = c++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

CPPFILS = Fixed.cpp main.cpp 


all:
	$(CXX) $(CPPFLAGS) $(CPPFILS) -o $(Name)

clean:
	rm -rf $(Name)

clean:
	rm -rf $(Name)

