Name = program_03

CXX = c++

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

CPPFILS = Fixed.cpp  Point.cpp  bsp.cpp   main.cpp

all:
	$(CXX) $(CPPFLAGS) $(CPPFILS) -o $(Name)

clean:
	rm -rf $(Name)

fclean: clean

re : fclean all